MODNAME      := inotify_hook

obj-m        += $(MODNAME).o
$(MODNAME)-y += main.o
$(MODNAME)-y += netlink_comm.o

ccflags-y   += -fno-stack-protector -fomit-frame-pointer
ldflags-y   += -T$(src)/khook/khook/engine.lds

LDFLAGS := $(ldflags-y) # legacy
KBUILD_CFLAGS := $(filter-out -pg,$(KBUILD_CFLAGS))
KBUILD_CFLAGS := $(filter-out -mfentry,$(KBUILD_CFLAGS))
