[package]
name = "serde_wrapper"
version = "1.0.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
serde_json = "1.0"

[dependencies.syn]
version = "1.0"
features = ["full", "extra-traits"]

[dependencies.serde]
version = "1.0"
features = ["derive"]
