[package]
name = "inotify-lookup"
version = "0.1.0"
authors = ["iamhyc <sudofree@163.com>"]
edition = "2018"

[lib]
name = "inotify_lookup"
crate-type = ["cdylib"]

[dependencies]
neli = "0.5.3"
maturin = "0.10.2"

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]
